/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PPostIdRouteImport } from './routes/p.$postId'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedReelsRouteImport } from './routes/_authenticated/reels'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedKidsRouteImport } from './routes/_authenticated/kids'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedNotificationsNewRouteImport } from './routes/_authenticated/notifications.new'
import { Route as AuthenticatedMessagesUserIdRouteImport } from './routes/_authenticated/messages.$userId'
import { Route as AuthenticatedMarketNewRouteImport } from './routes/_authenticated/market.new'
import { Route as AuthenticatedMarketListingIdRouteImport } from './routes/_authenticated/market.$listingId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PPostIdRoute = PPostIdRouteImport.update({
  id: '/p/$postId',
  path: '/p/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReelsRoute = AuthenticatedReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKidsRoute = AuthenticatedKidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedNotificationsNewRoute =
  AuthenticatedNotificationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedNotificationsRoute,
  } as any)
const AuthenticatedMessagesUserIdRoute =
  AuthenticatedMessagesUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedMarketNewRoute = AuthenticatedMarketNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedMarketRoute,
} as any)
const AuthenticatedMarketListingIdRoute =
  AuthenticatedMarketListingIdRouteImport.update({
    id: '/$listingId',
    path: '/$listingId',
    getParentRoute: () => AuthenticatedMarketRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/create': typeof AuthenticatedCreateRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/kids': typeof AuthenticatedKidsRoute
  '/live': typeof AuthenticatedLiveRoute
  '/market': typeof AuthenticatedMarketRouteWithChildren
  '/me': typeof AuthenticatedMeRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/reels': typeof AuthenticatedReelsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/p/$postId': typeof PPostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/market/$listingId': typeof AuthenticatedMarketListingIdRoute
  '/market/new': typeof AuthenticatedMarketNewRoute
  '/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/notifications/new': typeof AuthenticatedNotificationsNewRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/create': typeof AuthenticatedCreateRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/kids': typeof AuthenticatedKidsRoute
  '/live': typeof AuthenticatedLiveRoute
  '/market': typeof AuthenticatedMarketRouteWithChildren
  '/me': typeof AuthenticatedMeRoute
  '/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/reels': typeof AuthenticatedReelsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/p/$postId': typeof PPostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/market/$listingId': typeof AuthenticatedMarketListingIdRoute
  '/market/new': typeof AuthenticatedMarketNewRoute
  '/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/notifications/new': typeof AuthenticatedNotificationsNewRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/kids': typeof AuthenticatedKidsRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/market': typeof AuthenticatedMarketRouteWithChildren
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/_authenticated/reels': typeof AuthenticatedReelsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/p/$postId': typeof PPostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/_authenticated/market/$listingId': typeof AuthenticatedMarketListingIdRoute
  '/_authenticated/market/new': typeof AuthenticatedMarketNewRoute
  '/_authenticated/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/_authenticated/notifications/new': typeof AuthenticatedNotificationsNewRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/create'
    | '/discover'
    | '/feed'
    | '/kids'
    | '/live'
    | '/market'
    | '/me'
    | '/messages'
    | '/notifications'
    | '/reels'
    | '/search'
    | '/settings'
    | '/p/$postId'
    | '/u/$username'
    | '/market/$listingId'
    | '/market/new'
    | '/messages/$userId'
    | '/notifications/new'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/create'
    | '/discover'
    | '/feed'
    | '/kids'
    | '/live'
    | '/market'
    | '/me'
    | '/notifications'
    | '/reels'
    | '/search'
    | '/settings'
    | '/p/$postId'
    | '/u/$username'
    | '/market/$listingId'
    | '/market/new'
    | '/messages/$userId'
    | '/notifications/new'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/create'
    | '/_authenticated/discover'
    | '/_authenticated/feed'
    | '/_authenticated/kids'
    | '/_authenticated/live'
    | '/_authenticated/market'
    | '/_authenticated/me'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/reels'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/p/$postId'
    | '/u/$username'
    | '/_authenticated/market/$listingId'
    | '/_authenticated/market/new'
    | '/_authenticated/messages/$userId'
    | '/_authenticated/notifications/new'
    | '/_authenticated/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PPostIdRoute: typeof PPostIdRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$postId': {
      id: '/p/$postId'
      path: '/p/$postId'
      fullPath: '/p/$postId'
      preLoaderRoute: typeof PPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reels': {
      id: '/_authenticated/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AuthenticatedReelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kids': {
      id: '/_authenticated/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof AuthenticatedKidsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/notifications/new': {
      id: '/_authenticated/notifications/new'
      path: '/new'
      fullPath: '/notifications/new'
      preLoaderRoute: typeof AuthenticatedNotificationsNewRouteImport
      parentRoute: typeof AuthenticatedNotificationsRoute
    }
    '/_authenticated/messages/$userId': {
      id: '/_authenticated/messages/$userId'
      path: '/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof AuthenticatedMessagesUserIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/market/new': {
      id: '/_authenticated/market/new'
      path: '/new'
      fullPath: '/market/new'
      preLoaderRoute: typeof AuthenticatedMarketNewRouteImport
      parentRoute: typeof AuthenticatedMarketRoute
    }
    '/_authenticated/market/$listingId': {
      id: '/_authenticated/market/$listingId'
      path: '/$listingId'
      fullPath: '/market/$listingId'
      preLoaderRoute: typeof AuthenticatedMarketListingIdRouteImport
      parentRoute: typeof AuthenticatedMarketRoute
    }
  }
}

interface AuthenticatedMarketRouteChildren {
  AuthenticatedMarketListingIdRoute: typeof AuthenticatedMarketListingIdRoute
  AuthenticatedMarketNewRoute: typeof AuthenticatedMarketNewRoute
}

const AuthenticatedMarketRouteChildren: AuthenticatedMarketRouteChildren = {
  AuthenticatedMarketListingIdRoute: AuthenticatedMarketListingIdRoute,
  AuthenticatedMarketNewRoute: AuthenticatedMarketNewRoute,
}

const AuthenticatedMarketRouteWithChildren =
  AuthenticatedMarketRoute._addFileChildren(AuthenticatedMarketRouteChildren)

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesUserIdRoute: typeof AuthenticatedMessagesUserIdRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesUserIdRoute: AuthenticatedMessagesUserIdRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedNotificationsRouteChildren {
  AuthenticatedNotificationsNewRoute: typeof AuthenticatedNotificationsNewRoute
}

const AuthenticatedNotificationsRouteChildren: AuthenticatedNotificationsRouteChildren =
  {
    AuthenticatedNotificationsNewRoute: AuthenticatedNotificationsNewRoute,
  }

const AuthenticatedNotificationsRouteWithChildren =
  AuthenticatedNotificationsRoute._addFileChildren(
    AuthenticatedNotificationsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedKidsRoute: typeof AuthenticatedKidsRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRouteWithChildren
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRouteWithChildren
  AuthenticatedReelsRoute: typeof AuthenticatedReelsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedKidsRoute: AuthenticatedKidsRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedMarketRoute: AuthenticatedMarketRouteWithChildren,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRouteWithChildren,
  AuthenticatedReelsRoute: AuthenticatedReelsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PPostIdRoute: PPostIdRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
